development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:39f5b02740d037c54a08ed9046bbbf11@cod.redistogo.com:9421/
  channel_prefix: SlackersRow_production
